steps:
  # Step 0: Build the container using Google Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - 'build'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/converge/converge:${COMMIT_SHA}'
      - '--builder=gcr.io/buildpacks/builder:latest'
      - '--network=cloud-build'
      - '--env=NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL'
      - '--env=NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY'
      - '--env=NODE_ENV=production'

  # Step 1: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/converge/converge:${COMMIT_SHA}']

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'converge'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/converge/converge:${COMMIT_SHA}'
      - '--region=us-central1'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/converge/converge:${COMMIT_SHA}'