// apps/web/app/page.tsx
import { redirect } from 'next/navigation';
import { createClient } from '@supabase/supabase-js';
import { Button } from '@/components/ui/button'; // Assuming shadcn/ui or use standard <button>
import { ArrowRight, MapPin, Sparkles } from 'lucide-react';

// Initialize Supabase (Server-Side safe)
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY! // Safe to use in Server Component/Action
);

export default function LandingPage() {
  
  // Server Action to Create Session
  async function createNewSession() {
    'use server'; // Server Action
    
    // 1. Create a new session in DB
    const { data, error } = await supabase
      .from('sessions')
      .insert({}) // ID is auto-generated by UUIDv4 default in SQL
      .select('id')
      .single();

    if (error) {
      console.error('Failed to create session:', error);
      throw new Error('Failed to create session');
    }

    // 2. Redirect to the dynamic chat route
    redirect(`/chat/${data.id}`);
  }

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
      <div className="max-w-2xl text-center space-y-8">
        
        {/* Logo / Badge */}
        <div className="inline-flex items-center bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-sm font-semibold mb-4">
          <Sparkles className="w-4 h-4 mr-2" />
          Powered by Yelp AI
        </div>

        {/* Hero Text */}
        <h1 className="text-5xl md:text-6xl font-extrabold text-slate-900 tracking-tight">
          Converge
        </h1>
        <p className="text-xl text-slate-500 max-w-lg mx-auto leading-relaxed">
          The collaborative decision platform. Stop arguing about where to eat. 
          Let <strong>Connie</strong>, your AI concierge, handle the plans.
        </p>

        {/* Action Area */}
        <div className="bg-white p-6 rounded-2xl shadow-xl border border-slate-100 w-full max-w-md mx-auto">
          <div className="flex items-center mb-4 text-sm text-slate-400">
            <MapPin className="w-4 h-4 mr-1" />
            <span>Locating you in Austin, TX...</span>
          </div>
          
          <form action={createNewSession}>
            <Button 
              size="lg" 
              className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold h-12 text-lg"
            >
              Start New Session <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </form>
          
          <p className="mt-4 text-xs text-center text-slate-400">
            No login required. Instant access.
          </p>
        </div>
      </div>
    </div>
  );
}
